name: publish-homebridge-npm
on:
  push:
    branches:
      - feature/publish-homebridge-to-npm
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: npm publish
        working-directory: packages/homebridge
